import Footer from "../components/Footer"
import type { Metadata } from 'next'
import Navbar from "../components/Navbar"

export const metadata: Metadata = {
  title: 'Website Portofolio',
  description: 'Generated by create next app',
}

export default function Layout({children}: {children:React.ReactNode}) {
    
    return (
    <div>
        <Navbar/>
        {children}
        <Footer/>
    </div>

    )
}